### ISSUE TITLE
Initialising hotjar after cookie consent

### ISSUE THREAD

**Issue by georgibakken** [olavoparno/react-use-hotjar#13]
In nextjs, I have a cookie consent banner, where I want to initialize tracking (including hotjar), after an onClick.

However, it seems that with nextjs and hotjar, it needs to be initialized in `useEffect()`. Is there any way to initialize hotjar after an onclick event?

**Comment by olavoparno** [comment]
Hi, thanks for opening the issue.

I don't see a problem on initialising onClick. Have you tried it? It's not a must to start on useEffect. I should update the docs.

**Comment by georgibakken** [comment]
Thank you for the quick reply!

Yes, it works - now I tried it. I assumed it wouldn't, based on the documentation and that I couldn't make it work with [react-hotjar](https://www.npmjs.com/package/react-hotjar). Sorry about that :)

**Comment by olavoparno** [comment]
Oh no, no apologies needed, thank you! You are right, the documentation is biased to start it on app mounting so I definitely will update its documentation :) thank you again.

@all-contributors please add @georgibakken for doc and ideas
