### ISSUE TITLE
Support "stateChange"

### ISSUE THREAD

**Issue by ivan-kleshnin** [olavoparno/react-use-hotjar#3]
Hi there! My team is considering your library but can't currently use it due to lack of page events API.

In SPAs it's often desired and sometimes necessary to nofify Hotjar about route events. 

https://help.hotjar.com/hc/en-us/articles/360034216634-Hotjar-JavaScript-Functions-Reference#stateChange

Do you plan to support any wrapper for the following:

```js
hj('stateChange', relativePath)
```

?

**Comment by olavoparno** [comment]
@ivan-kleshnin hello, Ivan, thanks for the issue! I will definitely look into it but may I ask if you have control of those changes, i.e., through an useEffect of sorts? If you do you may call identify when it changes using the dependencies callback while I provide the ability in this lib.

**Comment by ivan-kleshnin** [comment]
Thanks for the quick reply Olavo. Yes, I have a control of routing and technically I can call `identify` multiple time.
Unfortunately I can't comment your idea as I have only a brief experience with Hotjar and it's not the most trivial tool. 
I'm not sure if repeated calls of `identify` will have the same effect or not but I'll try that if I have time.

**Comment by olavoparno** [comment]
@ivan-kleshnin I have added the functionality to the code. Thanks for the help and suggestion :) please do check for `stateChange` at version 1.1.0.

@all-contributors please add @ivan-kleshnin for ideas

**Comment by ivan-kleshnin** [comment]
Thank you, Olavo 👍  I'll take a look.
